# Generated by Django 4.2.5 on 2023-09-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='customer.menuitem'),
        ),
    ]
