# Generated by Django 4.2.5 on 2023-09-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='customer.size'),
        ),
    ]
