# Generated by Django 4.2.5 on 2023-10-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='otherImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='other_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
